CREATE TABLE sidebyside_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    price TEXT,
    description TEXT,
    link TEXT,
    category TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);

