CREATE TABLE sidebyside_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL UNIQUE,
  fullname TEXT NOT NULL,
  password TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE sidebyside_products
  ADD COLUMN
    author_id INTEGER REFERENCES sidebyside_users(id)
    ON DELETE SET NULL;