CREATE TABLE sidebyside_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    product_id INTEGER
        REFERENCES sidebyside_products(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES sidebyside_users(id) ON DELETE CASCADE NOT NULL
);